// src/lib/vp-pdf.ts
// Uses jspdf (already in deps). Call from client components only.
// import dynamically: const { generateVpPdf } = await import("@/lib/vp-pdf")

import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"

// ── Shared helpers ─────────────────────────────────────────────

const INR = (n: number) =>
    "Rs. " + n.toLocaleString("en-IN", { minimumFractionDigits: 2 })

function header(
    doc: jsPDF,
    title: string,
    docNum: string,
    company: string,
    gstin?: string,
    address?: string,
) {
    // Left: company branding
    doc.setFontSize(18).setFont("helvetica", "bold")
    doc.text(company, 14, 20)

    doc.setFontSize(9).setFont("helvetica", "normal").setTextColor(100)
    if (address) doc.text(address, 14, 27)
    if (gstin) doc.text("GSTIN: " + gstin, 14, 32)

    // Right: document type + number
    doc.setFontSize(22).setFont("helvetica", "bold").setTextColor(30)
    doc.text(title, 196, 20, { align: "right" })
    doc.setFontSize(10).setFont("helvetica", "normal").setTextColor(80)
    doc.text(docNum, 196, 28, { align: "right" })

    // Divider
    doc.setDrawColor(200).setLineWidth(0.3)
    doc.line(14, 38, 196, 38)

    doc.setTextColor(30) // reset
}

function metaBlock(
    doc: jsPDF,
    left: [string, string][],
    right: [string, string][],
    startY = 44,
) {
    let y = startY
    doc.setFontSize(9)
    for (const [k, v] of left) {
        doc.setFont("helvetica", "bold").text(k + ":", 14, y)
        doc.setFont("helvetica", "normal").text(v || "—", 55, y)
        y += 6
    }
    y = startY
    for (const [k, v] of right) {
        doc.setFont("helvetica", "bold").text(k + ":", 120, y)
        doc.setFont("helvetica", "normal").text(v || "—", 165, y)
        y += 6
    }
    return Math.max(startY + left.length * 6, startY + right.length * 6) + 4
}

function totalsBlock(
    doc: jsPDF,
    subtotal: number,
    discountAmount: number,
    taxRate: number,
    taxAmount: number,
    grandTotal: number,
    afterY: number,
) {
    const x1 = 130, x2 = 196
    let y = afterY + 4
    const taxableAmount = Math.max(0, subtotal - discountAmount)

    doc.setFontSize(9).setFont("helvetica", "normal")
    doc.text("Subtotal", x1, y); doc.text(INR(subtotal), x2, y, { align: "right" }); y += 6
    if (discountAmount > 0) {
        doc.text("Discount", x1, y); doc.text("- " + INR(discountAmount), x2, y, { align: "right" }); y += 6
        doc.text("Taxable Amount", x1, y); doc.text(INR(taxableAmount), x2, y, { align: "right" }); y += 6
    }
    doc.text(`GST (${taxRate}%)`, x1, y); doc.text(INR(taxAmount), x2, y, { align: "right" }); y += 2

    doc.setDrawColor(200).line(x1, y, x2, y); y += 5
    doc.setFont("helvetica", "bold").setFontSize(10)
    doc.text("Grand Total", x1, y); doc.text(INR(grandTotal), x2, y, { align: "right" }); y += 3

    doc.setDrawColor(200).line(x1, y, x2, y)
    return y
}

function footer(doc: jsPDF, notes?: string | null) {
    const pageH = doc.internal.pageSize.height
    doc.setDrawColor(200).setLineWidth(0.3)
    doc.line(14, pageH - 20, 196, pageH - 20)
    doc.setFontSize(8).setFont("helvetica", "normal").setTextColor(130)
    if (notes) {
        doc.text("Notes: " + notes, 14, pageH - 14, {
            maxWidth: 120,
        })
    }
    doc.text("Generated by AWL India Vendor Portal", 196, pageH - 14, {
        align: "right",
    })
}

// ── PURCHASE ORDER PDF ─────────────────────────────────────────

export interface PoPdfData {
    poNumber: string
    status: string
    vendorName: string
    vendorGst?: string
    vendorAddress?: string
    categoryName?: string | null
    deliveryDate?: Date | null
    deliveryAddress?: string | null
    createdAt: Date
    approvedBy?: string | null
    notes?: string | null
    subtotal: number
    discountAmount?: number
    taxRate: number
    taxAmount: number
    grandTotal: number
    items: {
        description: string
        qty: number
        unitPrice: number
        total: number
    }[]
    companyName?: string
    companyGstin?: string
    companyAddress?: string
}

export function generatePoPdf(data: PoPdfData): jsPDF {
    const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" })

    header(
        doc,
        "PURCHASE ORDER",
        data.poNumber,
        data.companyName ?? "AWL India Pvt. Ltd.",
        data.companyGstin,
        data.companyAddress,
    )

    const afterMeta = metaBlock(
        doc,
        [
            ["Vendor", data.vendorName],
            ["GST No.", data.vendorGst ?? "—"],
            ["Address", data.vendorAddress ?? "—"],
            ["Category", data.categoryName ?? "—"],
        ],
        [
            ["PO Number", data.poNumber],
            ["Date", new Date(data.createdAt).toLocaleDateString("en-IN")],
            ["Status", data.status],
            ["Delivery", data.deliveryDate
                ? new Date(data.deliveryDate).toLocaleDateString("en-IN")
                : "—"],
            ["Approved by", data.approvedBy ?? "Pending"],
        ],
    )

    // Delivery address
    let y = afterMeta
    if (data.deliveryAddress) {
        doc.setFontSize(9).setFont("helvetica", "bold").text("Delivery Address:", 14, y)
        doc.setFont("helvetica", "normal")
            .text(data.deliveryAddress, 14, y + 5, { maxWidth: 80 })
        y += 12
    }

    // Line items table
    autoTable(doc, {
        startY: y + 2,
        head: [["#", "Description", "Qty", "Unit Price", "Total"]],
        body: data.items.map((item, i) => [
            i + 1,
            item.description,
            item.qty,
            INR(item.unitPrice),
            INR(item.total),
        ]),
        headStyles: { fillColor: [30, 41, 59], textColor: 255, fontSize: 9 },
        bodyStyles: { fontSize: 9 },
        columnStyles: {
            0: { cellWidth: 10, halign: "center" },
            1: { cellWidth: 85 },
            2: { cellWidth: 15, halign: "center" },
            3: { cellWidth: 35, halign: "right" },
            4: { cellWidth: 35, halign: "right" },
        },
        theme: "striped",
    })

    const finalY = (doc as any).lastAutoTable.finalY + 4
    totalsBlock(doc, data.subtotal, data.discountAmount ?? 0, data.taxRate, data.taxAmount, data.grandTotal, finalY)
    footer(doc, data.notes)

    return doc
}

// ── PROFORMA INVOICE PDF ───────────────────────────────────────

export interface PiPdfData {
    piNumber: string
    status: string
    vendorName: string
    vendorGst?: string
    validityDate?: Date | null
    paymentTerms?: string | null
    categoryName?: string | null
    createdAt: Date
    approvedBy?: string | null
    notes?: string | null
    subtotal: number
    discountAmount?: number
    taxRate: number
    taxAmount: number
    grandTotal: number
    items: {
        description: string
        qty: number
        unitPrice: number
        total: number
    }[]
    companyName?: string
    companyGstin?: string
    companyAddress?: string
}

export function generatePiPdf(data: PiPdfData): jsPDF {
    const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" })

    header(
        doc,
        "PROFORMA INVOICE",
        data.piNumber,
        data.companyName ?? "AWL India Pvt. Ltd.",
        data.companyGstin,
        data.companyAddress,
    )

    const afterMeta = metaBlock(
        doc,
        [
            ["Vendor", data.vendorName],
            ["GST No.", data.vendorGst ?? "—"],
            ["Category", data.categoryName ?? "—"],
            ["Payment Terms", data.paymentTerms ?? "—"],
        ],
        [
            ["PI Number", data.piNumber],
            ["Date", new Date(data.createdAt).toLocaleDateString("en-IN")],
            ["Valid Until", data.validityDate
                ? new Date(data.validityDate).toLocaleDateString("en-IN")
                : "—"],
            ["Status", data.status],
            ["Approved by", data.approvedBy ?? "Pending"],
        ],
    )

    autoTable(doc, {
        startY: afterMeta + 2,
        head: [["#", "Description", "Qty", "Unit Price", "Total"]],
        body: data.items.map((item, i) => [
            i + 1,
            item.description,
            item.qty,
            INR(item.unitPrice),
            INR(item.total),
        ]),
        headStyles: { fillColor: [30, 41, 59], textColor: 255, fontSize: 9 },
        bodyStyles: { fontSize: 9 },
        columnStyles: {
            0: { cellWidth: 10, halign: "center" },
            1: { cellWidth: 85 },
            2: { cellWidth: 15, halign: "center" },
            3: { cellWidth: 35, halign: "right" },
            4: { cellWidth: 35, halign: "right" },
        },
        theme: "striped",
    })

    const finalY = (doc as any).lastAutoTable.finalY + 4
    totalsBlock(doc, data.subtotal, data.discountAmount ?? 0, data.taxRate, data.taxAmount, data.grandTotal, finalY)
    footer(doc, data.notes)

    return doc
}

// ── VENDOR INVOICE PDF ─────────────────────────────────────────

export interface InvoicePdfData {
    invoiceNumber: string
    status: string
    vendorName: string
    vendorGst?: string
    vendorAddress?: string
    billTo?: string | null
    billToGstin?: string | null
    billToAddress?: string | null
    poNumber?: string | null
    piNumber?: string | null
    createdAt: Date
    submittedAt?: Date | null
    notes?: string | null
    subtotal: number
    discountAmount: number
    taxRate: number
    taxAmount: number
    totalAmount: number
    items: {
        description: string
        qty: number
        unitPrice: number
        tax: number
        total: number
    }[]
    payments?: {
        amount: number
        paymentMode: string | null
        transactionRef: string | null
        paymentDate: Date | null
        status: string
    }[]
}

export function generateInvoicePdf(data: InvoicePdfData): jsPDF {
    const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" })

    // Vendor is the issuer here
    header(
        doc,
        "TAX INVOICE",
        data.invoiceNumber,
        data.vendorName,
        data.vendorGst,
        data.vendorAddress,
    )

    const afterMeta = metaBlock(
        doc,
        [
            ["Bill To", data.billTo ?? "AWL India Pvt. Ltd."],
            ["GSTIN", data.billToGstin ?? "—"],
            ["Address", data.billToAddress ?? "—"],
            ["PO Ref.", data.poNumber ?? "—"],
            ["PI Ref.", data.piNumber ?? "—"],
        ],
        [
            ["Invoice No.", data.invoiceNumber],
            ["Date", new Date(data.createdAt).toLocaleDateString("en-IN")],
            ["Submitted", data.submittedAt
                ? new Date(data.submittedAt).toLocaleDateString("en-IN")
                : "—"],
            ["Status", data.status],
        ],
    )

    autoTable(doc, {
        startY: afterMeta + 2,
        head: [["#", "Description", "Qty", "Unit Price", "Tax %", "Total"]],
        body: data.items.map((item, i) => [
            i + 1,
            item.description,
            item.qty,
            INR(item.unitPrice),
            item.tax + "%",
            INR(item.total),
        ]),
        headStyles: { fillColor: [30, 41, 59], textColor: 255, fontSize: 9 },
        bodyStyles: { fontSize: 9 },
        columnStyles: {
            0: { cellWidth: 10, halign: "center" },
            1: { cellWidth: 75 },
            2: { cellWidth: 15, halign: "center" },
            3: { cellWidth: 30, halign: "right" },
            4: { cellWidth: 15, halign: "center" },
            5: { cellWidth: 35, halign: "right" },
        },
        theme: "striped",
    })

    let y = (doc as any).lastAutoTable.finalY + 4
    y = totalsBlock(doc, data.subtotal, data.discountAmount, data.taxRate, data.taxAmount, data.totalAmount, y)

    // Payment history if any
    if (data.payments && data.payments.length > 0) {
        y += 8
        doc.setFontSize(10).setFont("helvetica", "bold").text("Payment History", 14, y)
        y += 2
        autoTable(doc, {
            startY: y,
            head: [["Amount", "Mode", "Ref No.", "Date", "Status"]],
            body: data.payments.map((p) => [
                INR(p.amount),
                p.paymentMode ?? "—",
                p.transactionRef ?? "—",
                p.paymentDate ? new Date(p.paymentDate).toLocaleDateString("en-IN") : "—",
                p.status,
            ]),
            headStyles: { fillColor: [16, 185, 129], textColor: 255, fontSize: 8 },
            bodyStyles: { fontSize: 8 },
            theme: "grid",
        })
    }

    footer(doc, data.notes)
    return doc
}
