import { GalleryVerticalEnd } from "lucide-react";
import type { Metadata } from "next";
import Image from "next/image";




export const metadata: Metadata = {
  title: "Login - Vendor Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="grid min-h-svh lg:grid-cols-2">
      <div className="flex flex-col gap-4 p-6 md:p-10">
        <div className="flex justify-center gap-2 md:justify-start">
          <a href="#" className="flex items-center gap-2 font-medium">
            <h2 className="text-xl font-bold">
              <span className="text-blue-600">Vendor</span> <span className=' text-foreground'>Portal</span>
            </h2>
          </a>
        </div>
        <div className="flex flex-1 items-center justify-center">
          <div className="w-full max-w-xs">
            {children}

          </div>
        </div>
      </div>
      <div className="bg-muted relative hidden lg:block">
        <Image
          height={100}
          width={100}
          src="/placeholder.svg"
          alt="Image"
          className="absolute inset-0 h-full w-full object-cover dark:brightness-[0.2] dark:grayscale"
        />
      </div>
    </div>
  );
}
